# Example configuration of registry `storage` secret
# Example for Amazon S3
#   See https://docs.docker.com/registry/storage-drivers/s3
#   See https://gitlab.com/gitlab-org/charts/gitlab/tree/master/doc/charts/registry/#storage
#   See https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/advanced/external-object-storage
s3:
  bucket: ${bucket_registry} 
  accesskey: ${scw_access_key} 
  secretkey: ${scw_secret_key}
  region: ${bucket_region}
  regionendpoint: "https://s3.${bucket_region}.scw.cloud"
  v4auth: true
